DATA={
	"ABROGATE": "To Revoke",
	"ANACHRONISM": "Something inappropriate for the given time period",
	"ARRANT": "Complete and wholly",
	"ARTLESS": "Without cunning or deceit",
	"ASPERITY": "Harsh in manner",
	"BELIE": "To give a false representation to",
	"BYZANTINE": "Complex and intricate",
	"CAJOLE": "Persuade by flattery or coaxing",
	"CONCILIATE": "To make peace with",
	"CONNECTICUTIAN": "A native or resident of Connecticut",
	"CONSANGUINEOUS": "Of the same blood or origin",
	"DEMAGOGUE": "A political leader who uses rhetoric to appeal to prejudices and desires of ordinary citizens",
	"DIATRIBE": "A verbal attack against a person",
	"DILATORY": "Wasting time",
	"EMBOURGEOISEMENT": "A shift to bourgeois values and practices",
	"EQUIVOCATE": "To speak vaguely, with intention of misleading someone",
	"FATUOS": "Devoid of intelligence",
	"GAFFE": "A socially awkward act",
	"GARRULOUS": "Talking too much",
	"HOI POLLOI": "The common people generally",
	"HUBRIS": "Overbearing pride",
	"Iconoclast": "Someone who criticizes or attacks cherished ideas and beliefs",
	"IMPEDIMENTA": "Things that impede",
	"INCHOATE": "Only partly in existence",
	"INDEFATIGABLE": "Showing sustained enthusiastic action with unflagging vitality",
	"INUNDATE": "Flooded",
	"INVECTIVE": "Abusive language",
	"MARTINET": "Someone who demands exact conformity to rules and forms",
	"MYRMECOPHILOUS": "Fond of ants",
	"NONPLUSSED": "Filled with bewilderment"
	}
a=input("Say:")
print(DATA[a])